### ISSUE TITLE
Cryptopia Issues

### ISSUE THREAD

**Issue by valent** [upggr/ielko-microtrader#1]
Many thanks for this wonderful work. Cryptopia has closed DOGE and all LTC markets, any plans for other markets like Bittrex and Bitmex.

**Comment by upggr** [comment]
I am very frustrated, cause I made all this, managed to triple my doge with a strategy in 10 days with increments of 30 doge bets and then cryptopia raised the minimum to 500. A few days later closed the market altogether. So, although i managed to get all the doge back, i am stuck now with all those stupid coins i cannot exchange to any market.
Anyway, I am preparing now the same program but compatible with nearly all exchanges, using the https://github.com/ccxt/ccxt project. so basically one parameter in the strategy will be the exchange you want to trade to, as simple as that. Problem is now i dont know where to trade too , where to experiment!
If you have any idea please suggest.
I am looking for an exchange that is supported by https://github.com/ccxt/ccxt and has at least 100 small coins, so i can run some 100s of experiments experiments with like 20$ while i am developing this.
I ve been trying yobit but is all problems, delays, stuck all the time. binance all is expensive.

**Comment by upggr** [comment]
oh i just saw you suggested bittrex and bitmex, I will release the script so you can try

**Comment by valent** [comment]
I think Bittrex can be a good starting point. Does the program work with only DOGE Markets? Bittrex has lots of small coins on Etherium market.

**Comment by valent** [comment]
I will be happy to test the software. Thanks a lot.

**Comment by upggr** [comment]
the program as it is now works only on cryptopia on any pair, but is useless as if you play on bitcoin the fees will be lots to just experiment. I will release the same for bittrex and you can test :) my problem is i dont have a bittrex account! https://support.bittrex.com/hc/en-us/articles/115003463331

**Comment by valent** [comment]
Let test the program, if all goes well we can get another bittrex account.

**Comment by upggr** [comment]
I am testing it on the BTC pairs now on cryptopia, as I made enough bitcoins before last week from doge (from 20$ to 120$) so now playing on 0.0005 increments


Regards,
Ioannis Kokkinis

**Comment by valent** [comment]
I am trying to run the current version but doesnt seem to me working. Am getting this error, 
"Fatal error: Call to undefined function random_bytes() in C:\Users\Val\Downloads\ielko-microtrader-master\bower_components\cryptopia-api-php\cryptopiaAPI.php on line 26"

I cant get the balance as well. Kindly help.

**Comment by upggr** [comment]
thats because you need php 7+...

**Comment by upggr** [comment]
if you do a git update, i added a mode where you can just run it with no order execution like this : php index-cli_test.php 0000000BTC_0000.00051_0000000010_0000000010_0000000.15_0000.00051_0000000000_0000000100_0000000020_0000000000
but is best if you use the php console rather than the browser.

**Comment by nandogameiro** [comment]
Thanks for this script @upggr I've started to use your script today on BTC market as DOGE on cryptopia has been closed. I ran it 4 or 5 times this morning and the script just executed 1 order but still no profits so far, I've been using this settings below:

`$hours =  48; 
$buyifabove =  10; 
$targetprofit =  0.10; 
$coinbet =  0.00050001; 
$target_coin_min_price =  0; 
$target_coin_max_price =  0.00000104; 
$lowvolume = 20; 
$open_order_coins_flag = 0; 
`

I will let you guys know if any profits be made during this weekend. I will keep playing :)

Thanks again for your script!

**Comment by upggr** [comment]
i made a channel at https://t.me/ielkomicrotrader   to share strategies etc , better than discussing on the issues at github :)

**Comment by upggr** [comment]
oh also note that there is a hardcoded variable that might prevent it from buying whatever, that I need to move it to the modifiable variables. before making the decision to buy in the core.php does this : && ($buy_sell_ratio > 0.7) && ($buy_sell_ratio < 0.9)       this buy_sell_ratio is a ratio of the sell and buy. for example if for a certain coin the buy price is 5 and the sell price is 3 , they are too far apart, so I am not playing at those, i made it 70% to 90%

**Comment by nandogameiro** [comment]
I've just joined the group, but we can't talk there because there is no option, you may have to authorize something there as admin :)

Thanks

**Comment by nandogameiro** [comment]
We can see your messages but we can't reply, see this screenshot https://prnt.sc/hzosji there is no field to write something :)
